package main

import (
	"bytes"
	"fmt"
)

var (
	// Name is application name.
	Name string

	// Version is application version.
	Version string

	// Revision describes current commit hash generated by `git describe --always`.
	Revision string
)

// OutputVersion retruns version string.
func OutputVersion() string {
	var buf bytes.Buffer

	fmt.Fprintf(&buf, "%s version %s", Name, Version)
	if len(Revision) > 0 {
		fmt.Fprintf(&buf, " (%s)", Revision)
	}
	fmt.Fprint(&buf, "\n")

	return buf.String()
}
